{% set name = "dtool_gui_tk" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-gui-tk/dtool-gui-tk-{{ version }}.tar.gz
  sha256: eb423a9e74d671583a8da1bdb08338a2906a1c6187daca7b2c7ad133bebb47df

build:
  number: 1
  entry_points:
    - dtool-tk=dtool_gui_tk.tkgui:tkgui
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dtool_info
    - dtoolcore >=3.18.0
    - jsonschema
    - python >={{ python_min }}
    - ruamel.yaml

test:
  imports:
    - dtool_gui_tk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jic-dtool/dtool-gui-tk
  summary: Graphical user interface for managing data using dtool
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
